// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'footer': string;
  'icon': string;
  'isActive': string;
  'logo': string;
  'profile': string;
  'search': string;
}
declare var cssExports: CssExports;
export = cssExports;
