// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bounce': string;
  'bounce-logo': string;
  'bounceLogo': string;
  'bouncelogo': string;
  'category-logo': string;
  'categoryLogo': string;
  'dimmed': string;
  'map-container': string;
  'mapContainer': string;
  'marker': string;
  'pin': string;
  'pulsate': string;
  'pulse': string;
  'pulse-landslides': string;
  'pulse-seaLakeIce': string;
  'pulse-severe-storms': string;
  'pulse-volcanoes': string;
  'pulse-wildfires': string;
  'pulseLandslides': string;
  'pulseSeaLakeIce': string;
  'pulseSevereStorms': string;
  'pulseVolcanoes': string;
  'pulseWildfires': string;
}
declare var cssExports: CssExports;
export = cssExports;
