// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'disabled': string;
  'link': string;
  'primary': string;
}
declare var cssExports: CssExports;
export = cssExports;
