// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'item': string;
  'label': string;
  'list': string;
}
declare var cssExports: CssExports;
export = cssExports;
