// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'invalid': string;
  'small': string;
}
declare var cssExports: CssExports;
export = cssExports;
