// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon-search': string;
  'iconSearch': string;
  'main-navigation-icon': string;
  'mainNavigationIcon': string;
  'svg-icon': string;
  'svgIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
